language: ruby

cache:
  bundler: true

before_install:
  - bundle --version
  - gem --version

sudo: false

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
